name: transporter
description: "An application for transferring orders and goods"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter

  firebase_messaging: ^15.0.2
  firebase_storage: ^12.1.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  dio: ^5.4.0
  google_maps_flutter: ^2.7.0
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  animated_text_kit: ^4.2.2
  intl: ^0.19.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#    - assets/fonts/
#    - assets/sounds/

#  fonts:
#    - family: Kanit
#      fonts:
#        - asset: assets/fonts/Kanit/Kanit-BoldItalic.ttf
#        - weight: 700
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
