// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYL5Lb6yIGhtQZyTx5eic4wTXIZxm2plQ',
    appId: '1:853020234250:web:1c0de569d5a231dae305f3',
    messagingSenderId: '853020234250',
    projectId: 'transporter-2633d',
    authDomain: 'transporter-2633d.firebaseapp.com',
    storageBucket: 'transporter-2633d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw1mOpAZA_Msw-ASFYzB_Yr7iuGVi_mUU',
    appId: '1:853020234250:android:aeea508198ecaab7e305f3',
    messagingSenderId: '853020234250',
    projectId: 'transporter-2633d',
    storageBucket: 'transporter-2633d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIaLt7GCWxUMqf6j5jltIzoUKsjkYahSE',
    appId: '1:853020234250:ios:32435cd5578b4989e305f3',
    messagingSenderId: '853020234250',
    projectId: 'transporter-2633d',
    storageBucket: 'transporter-2633d.appspot.com',
    iosBundleId: 'com.alidomainiraq.transporter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIaLt7GCWxUMqf6j5jltIzoUKsjkYahSE',
    appId: '1:853020234250:ios:edd3527df5004dc1e305f3',
    messagingSenderId: '853020234250',
    projectId: 'transporter-2633d',
    storageBucket: 'transporter-2633d.appspot.com',
    iosBundleId: 'com.alidomainiraq.transporter.RunnerTests',
  );
}
